name: io_queue
description: >
  Experimental File I/O with a Queue+Isolates.
version: 0.1.0
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/io_queue

environment:
  sdk: ">=2.0.0-dev <2.0.0"

depednencies:
  isolate: ^1.1.0
  pool: ^1.3.2

dev_dependencies:
  test: ^0.12.0
  test_descriptor: ^1.0.0
